const $=x=>document.getElementById(x),pick=a=>a[Math.random()*a.length|0],fmt=n=>Math.round(n).toLocaleString('ru-RU')+' ₽';
const RU_L=['А','В','Е','К','М','Н','О','Р','С','Т','У','Х'],LAT='ABCDEFGHJKLMNPRSTUVWXYZ'.split(''),DIG='0123456789'.split('');
const RU_R=[1,2,3,4,5,7,8,9,10,16,23,50,52,54,61,63,66,72,74,77,78,90,93,96,97,98,99,102,116,123,124,126,134,136,138,150,152,154,159,161,163,164,174,177,178,186,190,196,197,198,199,716,750,774,777,790,797,799];
const countries={RU:{name:'Россия',flag:'🇷🇺',code:'RUS'},DE:{name:'Германия',flag:'🇩🇪',code:'D'},US:{name:'США',flag:'🇺🇸',code:'USA'},GB:{name:'Великобритания',flag:'🇬🇧',code:'UK'},JP:{name:'Япония',flag:'🇯🇵',code:'JPN'},AE:{name:'ОАЭ',flag:'🇦🇪',code:'UAE'},FR:{name:'Франция',flag:'🇫🇷',code:'F'},IT:{name:'Италия',flag:'🇮🇹',code:'I'},NL:{name:'Нидерланды',flag:'🇳🇱',code:'NL'},CH:{name:'Швейцария',flag:'🇨🇭',code:'CH'},PL:{name:'Польша',flag:'🇵🇱',code:'PL'},KZ:{name:'Казахстан',flag:'🇰🇿',code:'KZ'}};
let state=JSON.parse(localStorage.getItem('avtonomerV3')||'null')||{balance:0,garage:[],rolls:0,best:0,sold:0,legendary:0,specials:0};let current=null,busy=false,filter='all',mode='WORLD';
function save(){localStorage.setItem('avtonomerV3',JSON.stringify(state))}
function rndDigits(n){return Array.from({length:n},()=>pick(DIG)).join('')}function rndLetters(n){return Array.from({length:n},()=>pick(LAT)).join('')}
function rarity(score,special){let tier=score>=18?4:score>=11?3:score>=6?2:score>=3?1:0;if(special)tier=Math.max(tier,3);let names=['Обычный','Красивый','Редкий','VIP','Легендарный'],cls=['common','nice','rare','vip','legend'],base=[1500,10000,50000,200000,750000][tier];return{tier,name:names[tier],cls:cls[tier],price:Math.round(base*(.75+Math.random()*.55)/500)*500}}
function scoreText(s){let digits=s.replace(/\D/g,''),score=1,tags=[];if(/(\d)\1\1/.test(digits)){score+=8;tags.push('повтор цифр')}if(/000|111|222|333|444|555|666|777|888|999/.test(digits)){score+=5;tags.push('тройка')}if(/123|234|345|456|567|678|789/.test(digits)){score+=4;tags.push('порядок')}if(/(^|\D)0*0?0?[1-9](\D|$)/.test(s)){score+=5;tags.push('малый номер')}return{score,tags}}
function specialType(){return pick(['Дипломатический','Правительственный','Электромобиль','Винтажный','Экспортный','Транзитный'])}
function genRU(){let a=pick(RU_L),b=pick(RU_L),c=pick(RU_L);if(Math.random()<.06)b=c=a;let n=Math.random()<.11?pick(['001','007','010','077','100','111','222','333','444','555','666','777','888','999']):String(1+Math.random()*999|0).padStart(3,'0'),text=a+' '+n+' '+b+c,s=scoreText(text);if(a===b&&b===c){s.score+=9;s.tags.push('три буквы')}return{text,side:String(pick(RU_R)),...s}}
function gen(code){if(code==='RU')return genRU();let text,side;switch(code){case'DE':text=rndLetters(1+Math.random()*2|0)+' '+rndLetters(1)+rndDigits(1+Math.random()*4|0);side=pick(['B','M','HH','K','F']);break;case'US':text=Math.random()<.2?pick(['1','7','777','VIP 1']):rndLetters(3)+' '+rndDigits(3);side=pick(['CA','NY','FL','TX']);break;case'GB':text=rndLetters(2)+rndDigits(2)+' '+rndLetters(3);side='UK';break;case'JP':text=pick(['品川','横浜','大阪','京都'])+' '+rndDigits(3);side=rndDigits(2)+'-'+rndDigits(2);break;case'AE':text=Math.random()<.22?String(1+Math.random()*99|0):pick(['A','B','C'])+' '+rndDigits(4);side=pick(['DUBAI','AD']);break;case'FR':text=rndLetters(2)+'-'+rndDigits(3)+'-'+rndLetters(2);side='F';break;case'IT':text=rndLetters(2)+' '+rndDigits(3)+' '+rndLetters(2);side='I';break;case'NL':text=rndLetters(2)+'-'+rndDigits(3)+'-'+rndLetters(1);side='NL';break;case'CH':text=pick(['ZH','BE','GE','VD','TI'])+' '+rndDigits(5);side='CH';break;case'PL':text=pick(['W','KR','PO','GD'])+' '+rndLetters(1)+rndDigits(4);side='PL';break;case'KZ':text=rndDigits(3)+' '+rndLetters(3);side=String(1+Math.random()*17|0).padStart(2,'0');break}let s=scoreText(text);return{text,side,...s}}
function make(){let code=mode==='WORLD'?pick(Object.keys(countries)):mode,x=gen(code),isSpecial=Math.random()<.035,type=isSpecial?specialType():null;if(isSpecial){x.score+=11;x.tags.push(type)}let g=rarity(x.score,isSpecial);if(code==='AE'&&/^\d{1,2}$/.test(x.text)){g.tier=4;g.name='Легендарный';g.cls='legend';g.price+=1500000;x.tags.push('короткий номер')}return{id:Date.now()+'-'+Math.random(),country:code,countryName:countries[code].name,flag:countries[code].flag,plateCode:countries[code].code,special:isSpecial,specialType:type,...x,...g}}
function show(x){$('num').textContent=x.text;$('reg').textContent=x.side;$('countryMark').textContent=x.flag+' '+x.plateCode;$('countryName').textContent=x.countryName+(x.special?' • '+x.specialType:'');$('rarity').textContent=x.name+(x.tags.length?' • '+x.tags.join(' • '):'');$('rarity').className='rarity '+x.cls;$('value').textContent='≈ '+fmt(x.price);$('plate').className='plate plate-'+x.country.toLowerCase()+(x.special?' specialPlate':'')}
function beep(f=420,d=.05){try{let C=AudioContext||webkitAudioContext,a=new C(),o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.frequency.value=f;g.gain.value=.02;o.start();g.gain.exponentialRampToValueAtTime(.001,a.currentTime+d);o.stop(a.currentTime+d)}catch(e){}}
async function roll(){if(busy)return;busy=true;$('keep').disabled=$('quickSell').disabled=$('roll').disabled=true;$('plate').classList.add('rolling');for(let i=0;i<13;i++){show(make());beep(220+i*20,.02);await new Promise(r=>setTimeout(r,38+i*7))}current=make();show(current);state.rolls++;state.best=Math.max(state.best,current.price);if(current.tier===4)state.legendary++;if(current.special)state.specials++;save();renderStats();$('keep').disabled=$('quickSell').disabled=$('roll').disabled=false;busy=false;beep(current.tier===4?900:520,.1)}
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1300)}
function keep(){if(!current)return;state.garage.push({...current});save();toast('Добавлено в гараж');current=null;$('keep').disabled=$('quickSell').disabled=true;render()}
function quickSell(){if(!current)return;state.balance+=current.price;state.sold++;toast('Продано за '+fmt(current.price));current=null;save();$('keep').disabled=$('quickSell').disabled=true;render()}
function sellGarage(id){let i=state.garage.findIndex(x=>String(x.id)===String(id));if(i<0)return,x=state.garage.splice(i,1)[0];state.balance+=x.price;state.sold++;save();render();toast('Продано за '+fmt(x.price))}
function renderStats(){$('balance').textContent=fmt(state.balance);$('garageCount').textContent='Гараж '+state.garage.length;$('rolls').textContent=state.rolls;$('best').textContent=fmt(state.best);$('sold').textContent=state.sold;$('legendary').textContent=state.legendary;$('specials').textContent=state.specials}
function render(){renderStats();let a=state.garage.slice().reverse().filter(x=>filter==='all'||filter==='rare'&&x.tier>=2||filter==='legend'&&x.tier===4||filter==='special'&&x.special);$('garage').innerHTML=a.length?a.map(x=>'<article class="item"><div class="countryTag">'+x.flag+' '+x.countryName+(x.special?' • '+x.specialType:'')+'</div><div class="miniPlate"><span>'+x.text+'</span><small>'+x.side+'</small></div><div class="row"><div><div class="'+x.cls+'" style="font-weight:900">'+x.name+'</div><div class="price">'+fmt(x.price)+'</div></div><button class="tiny" onclick="sellGarage(\''+x.id+'\')">Продать</button></div></article>').join(''):'<div class="empty">В этой категории пока ничего нет.</div>'}
$('roll').onclick=roll;$('keep').onclick=keep;$('quickSell').onclick=quickSell;$('country').onchange=e=>{mode=e.target.value;current=make();show(current)};document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.f;render()});render();current=make();show(current);